# Generated by Django 5.2.8 on 2025-11-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('published_date', models.CharField(blank=True, max_length=255, null=True)),
                ('is_summary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_id', models.BigIntegerField(default=0)),
                ('price_per_message', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=False)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TelegramChannel',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='apps.article')),
            ],
            options={
                'db_table': 'Summary',
            },
        ),
        migrations.CreateModel(
            name='TelegramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(default=0)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('cost_charged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_deliveries', to='apps.summary')),
                ('telegram_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_deliveries', to='apps.telegramchannel')),
            ],
            options={
                'db_table': 'TelegramDelivery',
            },
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channels', to='apps.topic'),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_classifications', to='apps.article')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_classifications', to='apps.topic')),
            ],
            options={
                'db_table': 'Classification',
                'unique_together': {('article', 'topic')},
            },
        ),
    ]
