# Generated by Django 5.2.8 on 2026-05-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_article_summarize_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='telegram_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='apps.telegramchannel'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='tone',
            field=models.CharField(choices=[('Formal', 'Formal'), ('Neutral', 'Neutral'), ('Informal', 'Informal')], default='Neutral', max_length=20),
        ),
    ]
