# Generated by Django 5.2.8 on 2026-05-18 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_summary_telegram_channel_telegramchannel_tone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('channel_name', 'Channel Name'), ('channel_id', 'Channel ID'), ('topic', 'Topic'), ('tone', 'Summary Tone')], help_text='The form field this video provides a hint for.', max_length=50, unique=True)),
                ('video_data', models.BinaryField(blank=True, help_text='Raw video file data.', null=True)),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the video, e.g., video/mp4.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
